export const UPDATE_FORM_FIELDS = "UPDATE_FORM_FIELDS";
export const UPDATE_IMAGE_URL = "UPDATE_IMAGE_URL";
export const IMAGE_VALIDATION_ERROR = "IMAGE_VALIDATION_ERROR";
export const ADD_NEW_HOBBY = "ADD_NEW_HOBBY";
export const UPDATE_HOBBIES = "UPDATE_HOBBIES";
export const UPDATE_HOBBY_ERROR = "UPDATE_HOBBY_ERROR";
